import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
    "en-GB": {
        // Navigation
        nav_examanswer: "ExamAnswer",
        nav_studytools: "Study Tools",
        nav_upgrade: "Upgrade",
        nav_settings: "Settings",
        nav_signin: "Sign In",
        
        // Landing
        landing_hero_title: "Write answers",
        landing_hero_highlight: "examiners reward",
        landing_hero_subtitle: "Transform your exam preparation with AI-powered answers crafted specifically for your exam board's marking criteria. GCSE, A-Level, AP, and more.",
        landing_cta_start: "Get Started Free",
        landing_cta_plans: "View Plans",
        landing_benefit_1: "Answers tailored to your specific exam board",
        landing_benefit_2: "Follow official marking scheme criteria",
        landing_benefit_3: "Get examiner-level insights on your work",
        landing_benefit_4: "Support for 10+ countries and education systems",
        landing_features_title: "Everything you need to excel",
        landing_features_subtitle: "Powerful tools designed for exam success",
        landing_cta_title: "Ready to ace your exams?",
        landing_cta_subtitle: "Join thousands of students who are already writing better exam answers with MarkUp.",
        landing_cta_button: "Start Writing Better Answers",
        
        // Auth
        auth_welcome: "Welcome back",
        auth_create: "Create account",
        auth_signin_subtitle: "Sign in to continue your exam prep",
        auth_signup_subtitle: "Start writing better exam answers today",
        auth_name: "Name",
        auth_name_placeholder: "Your name",
        auth_email: "Email",
        auth_email_placeholder: "you@example.com",
        auth_password: "Password",
        auth_signin_btn: "Sign In",
        auth_signup_btn: "Create Account",
        auth_signing_in: "Signing in...",
        auth_creating: "Creating account...",
        auth_no_account: "Don't have an account? Sign up",
        auth_have_account: "Already have an account? Sign in",
        
        // Settings
        settings_title: "Settings",
        settings_subtitle: "Configure your education level, exam board, and language preferences",
        settings_education_title: "Education Setup",
        settings_education_subtitle: "Your answers will be tailored to your specific exam board's requirements",
        settings_country: "Country",
        settings_country_placeholder: "Select your country",
        settings_level: "Education Level",
        settings_level_placeholder: "Select level",
        settings_level_first: "Select country first",
        settings_board: "Exam Board",
        settings_board_placeholder: "Select exam board",
        settings_board_first: "Select level first",
        settings_language_title: "Language",
        settings_language_subtitle: "Choose your preferred language for the interface",
        settings_appearance_title: "Appearance",
        settings_appearance_subtitle: "Switch between dark and light themes",
        settings_light: "Light",
        settings_dark: "Dark",
        settings_save: "Save & Continue",
        settings_saving: "Saving...",
        settings_summary: "Your answers will follow",
        settings_summary_in: "in",
        
        // ExamAnswer
        exam_title: "ExamAnswer",
        exam_subtitle: "Generate exam-board specific answers tailored for",
        exam_setup_required: "Setup Required",
        exam_setup_message: "Please configure your country, education level, and exam board first.",
        exam_go_settings: "Go to Settings",
        exam_your_question: "Your Question",
        exam_question_subtitle: "Enter your exam question and we'll generate a model answer",
        exam_subject: "Subject",
        exam_subject_placeholder: "Select subject",
        exam_task_type: "Task Type",
        exam_question: "Question",
        exam_question_placeholder: "Type or paste your exam question here...",
        exam_marks: "Marks (optional)",
        exam_marks_hint: "How many marks is this question worth?",
        exam_insight_title: "Examiner Insight",
        exam_insight_on: "Get grade prediction and improvement tips",
        exam_insight_off: "Requires Study+ or Pro tier",
        exam_generate: "Generate Answer",
        exam_generating: "Generating...",
        exam_model_answer: "Model Answer",
        exam_answer_placeholder: "Your model answer will appear here",
        exam_answer_hint: "Enter your question and click Generate",
        exam_copy: "Copy",
        
        // Study Tools
        tools_title: "Study Tools",
        tools_subtitle: "Powerful tools to enhance your exam preparation",
        tools_youtube_title: "YouTube → Notes",
        tools_youtube_desc: "Convert YouTube videos into structured study notes",
        tools_flashcards_title: "Flashcards",
        tools_flashcards_desc: "Generate AI-powered flashcards for any topic",
        tools_marker_title: "The Marker AI",
        tools_marker_desc: "Get expert feedback on why answers score highly",
        tools_required: "Required",
        tools_unlock: "Unlock",
        tools_unlock_all: "Unlock All Study Tools",
        tools_unlock_message: "Get access to YouTube Notes, Flashcards, The Marker AI, and more with Study+ or Pro.",
        
        // YouTube Notes
        youtube_title: "YouTube → Notes",
        youtube_subtitle: "Convert a YouTube video into clear, concise study notes",
        youtube_url: "YouTube URL",
        youtube_url_placeholder: "https://youtube.com/watch?v=...",
        youtube_or_paste: "Or paste transcript manually",
        youtube_manual_title: "Manual Transcript Required",
        youtube_manual_message: "YouTube is blocking automatic transcript extraction. Please copy the transcript from YouTube and paste it below.",
        youtube_manual_tip: "Tip: On YouTube, click \"...\" → \"Show transcript\" → Select all → Copy",
        youtube_paste_transcript: "Paste Transcript",
        youtube_paste_placeholder: "Paste the video transcript here...",
        youtube_back: "Back",
        youtube_generate: "Generate Notes",
        youtube_generating: "Generating...",
        youtube_notes: "Generated Notes",
        youtube_empty: "Paste a YouTube URL to generate study notes",
        youtube_empty_hint: "Works best with educational videos that have captions",
        youtube_extracting: "Extracting and summarizing video...",
        
        // Flashcards
        flashcards_title: "Generate Flashcards",
        flashcards_study_title: "Study Flashcards",
        flashcards_subtitle: "Create AI-powered flashcards for any topic",
        flashcards_study_subtitle: "Click on a card to flip it and reveal the answer",
        flashcards_subject: "Subject",
        flashcards_subject_placeholder: "e.g. Biology",
        flashcards_topic: "Topic",
        flashcards_topic_placeholder: "e.g. Cell Division",
        flashcards_count: "Number of Flashcards",
        flashcards_max: "Max: 100",
        flashcards_generate: "Generate",
        flashcards_generating: "Generating",
        flashcards_new: "Generate New Flashcards",
        flashcards_question: "Question",
        flashcards_answer: "Answer",
        flashcards_click_reveal: "Click to reveal answer",
        flashcards_click_question: "Click to see question",
        flashcards_card: "Card",
        flashcards_of: "of",
        flashcards_reset: "Reset",
        flashcards_previous: "Previous",
        flashcards_next: "Next",
        
        // The Marker AI
        marker_title: "The Marker AI",
        marker_subtitle: "Expert feedback for",
        marker_locked_message: "Get expert feedback on why answers score highly and what's missing for top marks.",
        marker_pro_feature: "Pro Feature",
        marker_unlock: "Unlock The Marker AI",
        marker_chat_title: "Chat with The Marker AI",
        marker_chat_subtitle: "Ask about mark schemes, answer techniques, or how to improve your responses",
        marker_empty: "Ask The Marker AI anything about exam technique",
        marker_hint_1: "How do I structure a 12-mark essay?",
        marker_hint_2: "What makes an A* evaluation answer?",
        marker_hint_3: "How do I hit all the assessment objectives?",
        marker_placeholder: "Ask The Marker AI...",
        
        // Upgrade
        upgrade_title: "Upgrade Your Exam Prep",
        upgrade_subtitle: "Unlock powerful features to write answers that examiners reward",
        upgrade_choose: "Choose Your Plan",
        upgrade_free: "Free",
        upgrade_free_desc: "Get started with basic exam answers",
        upgrade_studyplus: "Study+",
        upgrade_studyplus_desc: "Enhanced study tools and multi-subject support",
        upgrade_pro: "Pro",
        upgrade_pro_desc: "Everything plus AI Tutor for exam mastery",
        upgrade_popular: "Popular",
        upgrade_best: "Best Value",
        upgrade_current: "Current Plan",
        upgrade_to: "Upgrade to",
        upgrade_forever: "forever",
        upgrade_month: "/month",
        upgrade_cancel: "All plans include access to our core ExamAnswer feature. Cancel anytime — no questions asked.",
        upgrade_demo: "Demo mode: Upgrades are simulated. Payment integration available on request.",
        
        // Features
        feature_basic_exam: "Basic ExamAnswer",
        feature_limited_subjects: "Limited subjects",
        feature_no_history: "No answer history",
        feature_no_insight: "No Examiner Insight",
        feature_no_tools: "No Study Tools",
        feature_no_tutor: "No AI Tutor",
        feature_full_exam: "Full ExamAnswer",
        feature_multi_subject: "Multi-subject support",
        feature_youtube: "YouTube → Notes",
        feature_flashcards: "Flashcard Generator",
        feature_save: "Save & history",
        feature_insight: "Examiner Insight",
        feature_all_tools: "All Study+ tools",
        feature_marker: "AI Tutor — The Marker",
        feature_full_history: "Full answer history",
        feature_priority: "Priority support",
        
        // Common
        common_loading: "Loading...",
        common_error: "Something went wrong",
        common_success: "Success!",
        common_copied: "Copied to clipboard!",
        common_save: "Save",
        common_cancel: "Cancel",
        common_close: "Close",
        common_or: "or",
    },
    "en-US": {
        nav_examanswer: "ExamAnswer",
        nav_studytools: "Study Tools",
        nav_upgrade: "Upgrade",
        nav_settings: "Settings",
        nav_signin: "Sign In",
        landing_hero_title: "Write answers",
        landing_hero_highlight: "examiners reward",
        landing_hero_subtitle: "Transform your exam preparation with AI-powered answers crafted specifically for your exam board's marking criteria. GCSE, A-Level, AP, and more.",
        landing_cta_start: "Get Started Free",
        landing_cta_plans: "View Plans",
        landing_benefit_1: "Answers tailored to your specific exam board",
        landing_benefit_2: "Follow official marking scheme criteria",
        landing_benefit_3: "Get examiner-level insights on your work",
        landing_benefit_4: "Support for 10+ countries and education systems",
        landing_features_title: "Everything you need to excel",
        landing_features_subtitle: "Powerful tools designed for exam success",
        landing_cta_title: "Ready to ace your exams?",
        landing_cta_subtitle: "Join thousands of students who are already writing better exam answers with MarkUp.",
        landing_cta_button: "Start Writing Better Answers",
        auth_welcome: "Welcome back",
        auth_create: "Create account",
        auth_signin_subtitle: "Sign in to continue your exam prep",
        auth_signup_subtitle: "Start writing better exam answers today",
        auth_name: "Name",
        auth_name_placeholder: "Your name",
        auth_email: "Email",
        auth_email_placeholder: "you@example.com",
        auth_password: "Password",
        auth_signin_btn: "Sign In",
        auth_signup_btn: "Create Account",
        auth_signing_in: "Signing in...",
        auth_creating: "Creating account...",
        auth_no_account: "Don't have an account? Sign up",
        auth_have_account: "Already have an account? Sign in",
        settings_title: "Settings",
        settings_subtitle: "Configure your education level, exam board, and language preferences",
        settings_education_title: "Education Setup",
        settings_education_subtitle: "Your answers will be tailored to your specific exam board's requirements",
        settings_country: "Country",
        settings_country_placeholder: "Select your country",
        settings_level: "Education Level",
        settings_level_placeholder: "Select level",
        settings_level_first: "Select country first",
        settings_board: "Exam Board",
        settings_board_placeholder: "Select exam board",
        settings_board_first: "Select level first",
        settings_language_title: "Language",
        settings_language_subtitle: "Choose your preferred language for the interface",
        settings_appearance_title: "Appearance",
        settings_appearance_subtitle: "Switch between dark and light themes",
        settings_light: "Light",
        settings_dark: "Dark",
        settings_save: "Save & Continue",
        settings_saving: "Saving...",
        settings_summary: "Your answers will follow",
        settings_summary_in: "in",
        exam_title: "ExamAnswer",
        exam_subtitle: "Generate exam-board specific answers tailored for",
        exam_setup_required: "Setup Required",
        exam_setup_message: "Please configure your country, education level, and exam board first.",
        exam_go_settings: "Go to Settings",
        exam_your_question: "Your Question",
        exam_question_subtitle: "Enter your exam question and we'll generate a model answer",
        exam_subject: "Subject",
        exam_subject_placeholder: "Select subject",
        exam_task_type: "Task Type",
        exam_question: "Question",
        exam_question_placeholder: "Type or paste your exam question here...",
        exam_marks: "Marks (optional)",
        exam_marks_hint: "How many marks is this question worth?",
        exam_insight_title: "Examiner Insight",
        exam_insight_on: "Get grade prediction and improvement tips",
        exam_insight_off: "Requires Study+ or Pro tier",
        exam_generate: "Generate Answer",
        exam_generating: "Generating...",
        exam_model_answer: "Model Answer",
        exam_answer_placeholder: "Your model answer will appear here",
        exam_answer_hint: "Enter your question and click Generate",
        exam_copy: "Copy",
        tools_title: "Study Tools",
        tools_subtitle: "Powerful tools to enhance your exam preparation",
        tools_youtube_title: "YouTube → Notes",
        tools_youtube_desc: "Convert YouTube videos into structured study notes",
        tools_flashcards_title: "Flashcards",
        tools_flashcards_desc: "Generate AI-powered flashcards for any topic",
        tools_marker_title: "The Marker AI",
        tools_marker_desc: "Get expert feedback on why answers score highly",
        tools_required: "Required",
        tools_unlock: "Unlock",
        tools_unlock_all: "Unlock All Study Tools",
        tools_unlock_message: "Get access to YouTube Notes, Flashcards, The Marker AI, and more with Study+ or Pro.",
        youtube_title: "YouTube → Notes",
        youtube_subtitle: "Convert a YouTube video into clear, concise study notes",
        youtube_url: "YouTube URL",
        youtube_url_placeholder: "https://youtube.com/watch?v=...",
        youtube_or_paste: "Or paste transcript manually",
        youtube_manual_title: "Manual Transcript Required",
        youtube_manual_message: "YouTube is blocking automatic transcript extraction. Please copy the transcript from YouTube and paste it below.",
        youtube_manual_tip: "Tip: On YouTube, click \"...\" → \"Show transcript\" → Select all → Copy",
        youtube_paste_transcript: "Paste Transcript",
        youtube_paste_placeholder: "Paste the video transcript here...",
        youtube_back: "Back",
        youtube_generate: "Generate Notes",
        youtube_generating: "Generating...",
        youtube_notes: "Generated Notes",
        youtube_empty: "Paste a YouTube URL to generate study notes",
        youtube_empty_hint: "Works best with educational videos that have captions",
        youtube_extracting: "Extracting and summarizing video...",
        flashcards_title: "Generate Flashcards",
        flashcards_study_title: "Study Flashcards",
        flashcards_subtitle: "Create AI-powered flashcards for any topic",
        flashcards_study_subtitle: "Click on a card to flip it and reveal the answer",
        flashcards_subject: "Subject",
        flashcards_subject_placeholder: "e.g. Biology",
        flashcards_topic: "Topic",
        flashcards_topic_placeholder: "e.g. Cell Division",
        flashcards_count: "Number of Flashcards",
        flashcards_max: "Max: 100",
        flashcards_generate: "Generate",
        flashcards_generating: "Generating",
        flashcards_new: "Generate New Flashcards",
        flashcards_question: "Question",
        flashcards_answer: "Answer",
        flashcards_click_reveal: "Click to reveal answer",
        flashcards_click_question: "Click to see question",
        flashcards_card: "Card",
        flashcards_of: "of",
        flashcards_reset: "Reset",
        flashcards_previous: "Previous",
        flashcards_next: "Next",
        marker_title: "The Marker AI",
        marker_subtitle: "Expert feedback for",
        marker_locked_message: "Get expert feedback on why answers score highly and what's missing for top marks.",
        marker_pro_feature: "Pro Feature",
        marker_unlock: "Unlock The Marker AI",
        marker_chat_title: "Chat with The Marker AI",
        marker_chat_subtitle: "Ask about mark schemes, answer techniques, or how to improve your responses",
        marker_empty: "Ask The Marker AI anything about exam technique",
        marker_hint_1: "How do I structure a 12-mark essay?",
        marker_hint_2: "What makes an A* evaluation answer?",
        marker_hint_3: "How do I hit all the assessment objectives?",
        marker_placeholder: "Ask The Marker AI...",
        upgrade_title: "Upgrade Your Exam Prep",
        upgrade_subtitle: "Unlock powerful features to write answers that examiners reward",
        upgrade_choose: "Choose Your Plan",
        upgrade_free: "Free",
        upgrade_free_desc: "Get started with basic exam answers",
        upgrade_studyplus: "Study+",
        upgrade_studyplus_desc: "Enhanced study tools and multi-subject support",
        upgrade_pro: "Pro",
        upgrade_pro_desc: "Everything plus AI Tutor for exam mastery",
        upgrade_popular: "Popular",
        upgrade_best: "Best Value",
        upgrade_current: "Current Plan",
        upgrade_to: "Upgrade to",
        upgrade_forever: "forever",
        upgrade_month: "/month",
        upgrade_cancel: "All plans include access to our core ExamAnswer feature. Cancel anytime — no questions asked.",
        upgrade_demo: "Demo mode: Upgrades are simulated. Payment integration available on request.",
        feature_basic_exam: "Basic ExamAnswer",
        feature_limited_subjects: "Limited subjects",
        feature_no_history: "No answer history",
        feature_no_insight: "No Examiner Insight",
        feature_no_tools: "No Study Tools",
        feature_no_tutor: "No AI Tutor",
        feature_full_exam: "Full ExamAnswer",
        feature_multi_subject: "Multi-subject support",
        feature_youtube: "YouTube → Notes",
        feature_flashcards: "Flashcard Generator",
        feature_save: "Save & history",
        feature_insight: "Examiner Insight",
        feature_all_tools: "All Study+ tools",
        feature_marker: "AI Tutor — The Marker",
        feature_full_history: "Full answer history",
        feature_priority: "Priority support",
        common_loading: "Loading...",
        common_error: "Something went wrong",
        common_success: "Success!",
        common_copied: "Copied to clipboard!",
        common_save: "Save",
        common_cancel: "Cancel",
        common_close: "Close",
        common_or: "or",
    },
    "fr": {
        nav_examanswer: "RéponseExam",
        nav_studytools: "Outils d'étude",
        nav_upgrade: "Améliorer",
        nav_settings: "Paramètres",
        nav_signin: "Connexion",
        landing_hero_title: "Rédigez des réponses que",
        landing_hero_highlight: "les examinateurs récompensent",
        landing_hero_subtitle: "Transformez votre préparation aux examens avec des réponses générées par IA, spécifiquement conçues pour les critères de notation de votre commission d'examen.",
        landing_cta_start: "Commencer gratuitement",
        landing_cta_plans: "Voir les plans",
        landing_benefit_1: "Réponses adaptées à votre commission d'examen",
        landing_benefit_2: "Suivez les critères officiels de notation",
        landing_benefit_3: "Obtenez des conseils d'examinateur",
        landing_benefit_4: "Support pour 10+ pays et systèmes éducatifs",
        landing_features_title: "Tout ce dont vous avez besoin pour exceller",
        landing_features_subtitle: "Des outils puissants conçus pour réussir vos examens",
        landing_cta_title: "Prêt à réussir vos examens ?",
        landing_cta_subtitle: "Rejoignez des milliers d'étudiants qui rédigent déjà de meilleures réponses avec MarkUp.",
        landing_cta_button: "Commencer à mieux répondre",
        auth_welcome: "Bon retour",
        auth_create: "Créer un compte",
        auth_signin_subtitle: "Connectez-vous pour continuer votre préparation",
        auth_signup_subtitle: "Commencez à rédiger de meilleures réponses aujourd'hui",
        auth_name: "Nom",
        auth_name_placeholder: "Votre nom",
        auth_email: "Email",
        auth_email_placeholder: "vous@exemple.com",
        auth_password: "Mot de passe",
        auth_signin_btn: "Se connecter",
        auth_signup_btn: "Créer un compte",
        auth_signing_in: "Connexion...",
        auth_creating: "Création du compte...",
        auth_no_account: "Pas de compte ? Inscrivez-vous",
        auth_have_account: "Déjà un compte ? Connectez-vous",
        settings_title: "Paramètres",
        settings_subtitle: "Configurez votre niveau d'études, commission d'examen et langue",
        settings_education_title: "Configuration éducative",
        settings_education_subtitle: "Vos réponses seront adaptées aux exigences de votre commission",
        settings_country: "Pays",
        settings_country_placeholder: "Sélectionnez votre pays",
        settings_level: "Niveau d'études",
        settings_level_placeholder: "Sélectionnez le niveau",
        settings_level_first: "Sélectionnez d'abord le pays",
        settings_board: "Commission d'examen",
        settings_board_placeholder: "Sélectionnez la commission",
        settings_board_first: "Sélectionnez d'abord le niveau",
        settings_language_title: "Langue",
        settings_language_subtitle: "Choisissez votre langue préférée pour l'interface",
        settings_appearance_title: "Apparence",
        settings_appearance_subtitle: "Basculer entre les thèmes clair et sombre",
        settings_light: "Clair",
        settings_dark: "Sombre",
        settings_save: "Enregistrer et continuer",
        settings_saving: "Enregistrement...",
        settings_summary: "Vos réponses suivront",
        settings_summary_in: "en",
        exam_title: "RéponseExam",
        exam_subtitle: "Générez des réponses spécifiques pour",
        exam_setup_required: "Configuration requise",
        exam_setup_message: "Veuillez d'abord configurer votre pays, niveau d'études et commission d'examen.",
        exam_go_settings: "Aller aux paramètres",
        exam_your_question: "Votre question",
        exam_question_subtitle: "Entrez votre question d'examen et nous générerons une réponse modèle",
        exam_subject: "Matière",
        exam_subject_placeholder: "Sélectionnez la matière",
        exam_task_type: "Type de tâche",
        exam_question: "Question",
        exam_question_placeholder: "Tapez ou collez votre question d'examen ici...",
        exam_marks: "Points (optionnel)",
        exam_marks_hint: "Combien de points vaut cette question ?",
        exam_insight_title: "Analyse d'examinateur",
        exam_insight_on: "Obtenez une prédiction de note et des conseils",
        exam_insight_off: "Nécessite Study+ ou Pro",
        exam_generate: "Générer la réponse",
        exam_generating: "Génération...",
        exam_model_answer: "Réponse modèle",
        exam_answer_placeholder: "Votre réponse modèle apparaîtra ici",
        exam_answer_hint: "Entrez votre question et cliquez sur Générer",
        exam_copy: "Copier",
        tools_title: "Outils d'étude",
        tools_subtitle: "Des outils puissants pour améliorer votre préparation",
        tools_youtube_title: "YouTube → Notes",
        tools_youtube_desc: "Convertissez des vidéos YouTube en notes structurées",
        tools_flashcards_title: "Cartes mémoire",
        tools_flashcards_desc: "Générez des cartes mémoire par IA",
        tools_marker_title: "The Marker AI",
        tools_marker_desc: "Obtenez des retours d'expert sur vos réponses",
        tools_required: "Requis",
        tools_unlock: "Débloquer",
        tools_unlock_all: "Débloquer tous les outils",
        tools_unlock_message: "Accédez aux Notes YouTube, Cartes mémoire, The Marker AI avec Study+ ou Pro.",
        youtube_title: "YouTube → Notes",
        youtube_subtitle: "Convertissez une vidéo en notes claires et concises",
        youtube_url: "URL YouTube",
        youtube_url_placeholder: "https://youtube.com/watch?v=...",
        youtube_or_paste: "Ou collez la transcription manuellement",
        youtube_manual_title: "Transcription manuelle requise",
        youtube_manual_message: "YouTube bloque l'extraction automatique. Copiez la transcription et collez-la ci-dessous.",
        youtube_manual_tip: "Astuce : Sur YouTube, cliquez \"...\" → \"Afficher la transcription\" → Tout sélectionner → Copier",
        youtube_paste_transcript: "Coller la transcription",
        youtube_paste_placeholder: "Collez la transcription ici...",
        youtube_back: "Retour",
        youtube_generate: "Générer les notes",
        youtube_generating: "Génération...",
        youtube_notes: "Notes générées",
        youtube_empty: "Collez une URL YouTube pour générer des notes",
        youtube_empty_hint: "Fonctionne mieux avec des vidéos éducatives sous-titrées",
        youtube_extracting: "Extraction et résumé de la vidéo...",
        flashcards_title: "Générer des cartes mémoire",
        flashcards_study_title: "Étudier les cartes",
        flashcards_subtitle: "Créez des cartes mémoire par IA sur n'importe quel sujet",
        flashcards_study_subtitle: "Cliquez sur une carte pour la retourner",
        flashcards_subject: "Matière",
        flashcards_subject_placeholder: "ex. Biologie",
        flashcards_topic: "Sujet",
        flashcards_topic_placeholder: "ex. Division cellulaire",
        flashcards_count: "Nombre de cartes",
        flashcards_max: "Max : 100",
        flashcards_generate: "Générer",
        flashcards_generating: "Génération",
        flashcards_new: "Nouvelles cartes",
        flashcards_question: "Question",
        flashcards_answer: "Réponse",
        flashcards_click_reveal: "Cliquez pour révéler",
        flashcards_click_question: "Cliquez pour voir la question",
        flashcards_card: "Carte",
        flashcards_of: "sur",
        flashcards_reset: "Réinitialiser",
        flashcards_previous: "Précédent",
        flashcards_next: "Suivant",
        marker_title: "The Marker AI",
        marker_subtitle: "Retours d'expert pour",
        marker_locked_message: "Obtenez des retours d'expert sur pourquoi certaines réponses obtiennent de bonnes notes.",
        marker_pro_feature: "Fonctionnalité Pro",
        marker_unlock: "Débloquer The Marker AI",
        marker_chat_title: "Discuter avec The Marker AI",
        marker_chat_subtitle: "Posez des questions sur les barèmes et techniques de réponse",
        marker_empty: "Posez n'importe quelle question sur les techniques d'examen",
        marker_hint_1: "Comment structurer une dissertation de 12 points ?",
        marker_hint_2: "Qu'est-ce qui fait une réponse A* ?",
        marker_hint_3: "Comment atteindre tous les objectifs d'évaluation ?",
        marker_placeholder: "Posez votre question...",
        upgrade_title: "Améliorez votre préparation",
        upgrade_subtitle: "Débloquez des fonctionnalités puissantes",
        upgrade_choose: "Choisissez votre plan",
        upgrade_free: "Gratuit",
        upgrade_free_desc: "Commencez avec les réponses de base",
        upgrade_studyplus: "Study+",
        upgrade_studyplus_desc: "Outils d'étude améliorés",
        upgrade_pro: "Pro",
        upgrade_pro_desc: "Tout inclus avec AI Tutor",
        upgrade_popular: "Populaire",
        upgrade_best: "Meilleur rapport",
        upgrade_current: "Plan actuel",
        upgrade_to: "Passer à",
        upgrade_forever: "pour toujours",
        upgrade_month: "/mois",
        upgrade_cancel: "Tous les plans incluent ExamAnswer. Annulez à tout moment.",
        upgrade_demo: "Mode démo : Les mises à niveau sont simulées.",
        feature_basic_exam: "ExamAnswer basique",
        feature_limited_subjects: "Matières limitées",
        feature_no_history: "Pas d'historique",
        feature_no_insight: "Pas d'analyse",
        feature_no_tools: "Pas d'outils",
        feature_no_tutor: "Pas d'AI Tutor",
        feature_full_exam: "ExamAnswer complet",
        feature_multi_subject: "Multi-matières",
        feature_youtube: "YouTube → Notes",
        feature_flashcards: "Cartes mémoire",
        feature_save: "Sauvegarde et historique",
        feature_insight: "Analyse d'examinateur",
        feature_all_tools: "Tous les outils Study+",
        feature_marker: "AI Tutor — The Marker",
        feature_full_history: "Historique complet",
        feature_priority: "Support prioritaire",
        common_loading: "Chargement...",
        common_error: "Une erreur s'est produite",
        common_success: "Succès !",
        common_copied: "Copié !",
        common_save: "Enregistrer",
        common_cancel: "Annuler",
        common_close: "Fermer",
        common_or: "ou",
    },
    "es": {
        nav_examanswer: "RespuestaExam",
        nav_studytools: "Herramientas",
        nav_upgrade: "Mejorar",
        nav_settings: "Ajustes",
        nav_signin: "Iniciar sesión",
        landing_hero_title: "Escribe respuestas que",
        landing_hero_highlight: "los examinadores premian",
        landing_hero_subtitle: "Transforma tu preparación con respuestas generadas por IA, diseñadas específicamente para los criterios de tu junta examinadora.",
        landing_cta_start: "Empezar gratis",
        landing_cta_plans: "Ver planes",
        landing_benefit_1: "Respuestas adaptadas a tu junta examinadora",
        landing_benefit_2: "Sigue los criterios oficiales de calificación",
        landing_benefit_3: "Obtén consejos de nivel examinador",
        landing_benefit_4: "Soporte para 10+ países y sistemas educativos",
        landing_features_title: "Todo lo que necesitas para sobresalir",
        landing_features_subtitle: "Herramientas poderosas diseñadas para el éxito",
        landing_cta_title: "¿Listo para aprobar tus exámenes?",
        landing_cta_subtitle: "Únete a miles de estudiantes que ya escriben mejores respuestas con MarkUp.",
        landing_cta_button: "Empieza a escribir mejor",
        auth_welcome: "Bienvenido de nuevo",
        auth_create: "Crear cuenta",
        auth_signin_subtitle: "Inicia sesión para continuar tu preparación",
        auth_signup_subtitle: "Empieza a escribir mejores respuestas hoy",
        auth_name: "Nombre",
        auth_name_placeholder: "Tu nombre",
        auth_email: "Correo",
        auth_email_placeholder: "tu@ejemplo.com",
        auth_password: "Contraseña",
        auth_signin_btn: "Iniciar sesión",
        auth_signup_btn: "Crear cuenta",
        auth_signing_in: "Iniciando...",
        auth_creating: "Creando cuenta...",
        auth_no_account: "¿No tienes cuenta? Regístrate",
        auth_have_account: "¿Ya tienes cuenta? Inicia sesión",
        settings_title: "Ajustes",
        settings_subtitle: "Configura tu nivel educativo, junta examinadora e idioma",
        settings_education_title: "Configuración educativa",
        settings_education_subtitle: "Tus respuestas se adaptarán a tu junta examinadora",
        settings_country: "País",
        settings_country_placeholder: "Selecciona tu país",
        settings_level: "Nivel educativo",
        settings_level_placeholder: "Selecciona nivel",
        settings_level_first: "Selecciona país primero",
        settings_board: "Junta examinadora",
        settings_board_placeholder: "Selecciona junta",
        settings_board_first: "Selecciona nivel primero",
        settings_language_title: "Idioma",
        settings_language_subtitle: "Elige tu idioma preferido para la interfaz",
        settings_appearance_title: "Apariencia",
        settings_appearance_subtitle: "Cambiar entre tema claro y oscuro",
        settings_light: "Claro",
        settings_dark: "Oscuro",
        settings_save: "Guardar y continuar",
        settings_saving: "Guardando...",
        settings_summary: "Tus respuestas seguirán",
        settings_summary_in: "en",
        exam_title: "RespuestaExam",
        exam_subtitle: "Genera respuestas específicas para",
        exam_setup_required: "Configuración requerida",
        exam_setup_message: "Por favor configura tu país, nivel educativo y junta examinadora.",
        exam_go_settings: "Ir a ajustes",
        exam_your_question: "Tu pregunta",
        exam_question_subtitle: "Ingresa tu pregunta y generaremos una respuesta modelo",
        exam_subject: "Asignatura",
        exam_subject_placeholder: "Selecciona asignatura",
        exam_task_type: "Tipo de tarea",
        exam_question: "Pregunta",
        exam_question_placeholder: "Escribe o pega tu pregunta aquí...",
        exam_marks: "Puntos (opcional)",
        exam_marks_hint: "¿Cuántos puntos vale esta pregunta?",
        exam_insight_title: "Análisis del examinador",
        exam_insight_on: "Obtén predicción de nota y consejos",
        exam_insight_off: "Requiere Study+ o Pro",
        exam_generate: "Generar respuesta",
        exam_generating: "Generando...",
        exam_model_answer: "Respuesta modelo",
        exam_answer_placeholder: "Tu respuesta modelo aparecerá aquí",
        exam_answer_hint: "Ingresa tu pregunta y haz clic en Generar",
        exam_copy: "Copiar",
        tools_title: "Herramientas de estudio",
        tools_subtitle: "Herramientas poderosas para mejorar tu preparación",
        tools_youtube_title: "YouTube → Notas",
        tools_youtube_desc: "Convierte videos de YouTube en notas estructuradas",
        tools_flashcards_title: "Tarjetas",
        tools_flashcards_desc: "Genera tarjetas de estudio con IA",
        tools_marker_title: "The Marker AI",
        tools_marker_desc: "Obtén retroalimentación experta sobre tus respuestas",
        tools_required: "Requerido",
        tools_unlock: "Desbloquear",
        tools_unlock_all: "Desbloquear todas las herramientas",
        tools_unlock_message: "Accede a Notas YouTube, Tarjetas, The Marker AI con Study+ o Pro.",
        youtube_title: "YouTube → Notas",
        youtube_subtitle: "Convierte un video en notas claras y concisas",
        youtube_url: "URL de YouTube",
        youtube_url_placeholder: "https://youtube.com/watch?v=...",
        youtube_or_paste: "O pega la transcripción manualmente",
        youtube_manual_title: "Transcripción manual requerida",
        youtube_manual_message: "YouTube está bloqueando la extracción automática. Copia la transcripción y pégala abajo.",
        youtube_manual_tip: "Consejo: En YouTube, haz clic \"...\" → \"Mostrar transcripción\" → Seleccionar todo → Copiar",
        youtube_paste_transcript: "Pegar transcripción",
        youtube_paste_placeholder: "Pega la transcripción aquí...",
        youtube_back: "Volver",
        youtube_generate: "Generar notas",
        youtube_generating: "Generando...",
        youtube_notes: "Notas generadas",
        youtube_empty: "Pega una URL de YouTube para generar notas",
        youtube_empty_hint: "Funciona mejor con videos educativos con subtítulos",
        youtube_extracting: "Extrayendo y resumiendo video...",
        flashcards_title: "Generar tarjetas",
        flashcards_study_title: "Estudiar tarjetas",
        flashcards_subtitle: "Crea tarjetas con IA sobre cualquier tema",
        flashcards_study_subtitle: "Haz clic en una tarjeta para voltearla",
        flashcards_subject: "Asignatura",
        flashcards_subject_placeholder: "ej. Biología",
        flashcards_topic: "Tema",
        flashcards_topic_placeholder: "ej. División celular",
        flashcards_count: "Número de tarjetas",
        flashcards_max: "Máx: 100",
        flashcards_generate: "Generar",
        flashcards_generating: "Generando",
        flashcards_new: "Nuevas tarjetas",
        flashcards_question: "Pregunta",
        flashcards_answer: "Respuesta",
        flashcards_click_reveal: "Clic para revelar",
        flashcards_click_question: "Clic para ver pregunta",
        flashcards_card: "Tarjeta",
        flashcards_of: "de",
        flashcards_reset: "Reiniciar",
        flashcards_previous: "Anterior",
        flashcards_next: "Siguiente",
        marker_title: "The Marker AI",
        marker_subtitle: "Retroalimentación experta para",
        marker_locked_message: "Obtén retroalimentación experta sobre por qué ciertas respuestas obtienen buenas notas.",
        marker_pro_feature: "Función Pro",
        marker_unlock: "Desbloquear The Marker AI",
        marker_chat_title: "Chatea con The Marker AI",
        marker_chat_subtitle: "Pregunta sobre criterios y técnicas de respuesta",
        marker_empty: "Pregunta cualquier cosa sobre técnicas de examen",
        marker_hint_1: "¿Cómo estructurar un ensayo de 12 puntos?",
        marker_hint_2: "¿Qué hace una respuesta A*?",
        marker_hint_3: "¿Cómo alcanzar todos los objetivos de evaluación?",
        marker_placeholder: "Haz tu pregunta...",
        upgrade_title: "Mejora tu preparación",
        upgrade_subtitle: "Desbloquea funciones poderosas",
        upgrade_choose: "Elige tu plan",
        upgrade_free: "Gratis",
        upgrade_free_desc: "Empieza con respuestas básicas",
        upgrade_studyplus: "Study+",
        upgrade_studyplus_desc: "Herramientas de estudio mejoradas",
        upgrade_pro: "Pro",
        upgrade_pro_desc: "Todo incluido con AI Tutor",
        upgrade_popular: "Popular",
        upgrade_best: "Mejor valor",
        upgrade_current: "Plan actual",
        upgrade_to: "Mejorar a",
        upgrade_forever: "para siempre",
        upgrade_month: "/mes",
        upgrade_cancel: "Todos los planes incluyen ExamAnswer. Cancela cuando quieras.",
        upgrade_demo: "Modo demo: Las mejoras son simuladas.",
        feature_basic_exam: "ExamAnswer básico",
        feature_limited_subjects: "Asignaturas limitadas",
        feature_no_history: "Sin historial",
        feature_no_insight: "Sin análisis",
        feature_no_tools: "Sin herramientas",
        feature_no_tutor: "Sin AI Tutor",
        feature_full_exam: "ExamAnswer completo",
        feature_multi_subject: "Multi-asignatura",
        feature_youtube: "YouTube → Notas",
        feature_flashcards: "Tarjetas de estudio",
        feature_save: "Guardar e historial",
        feature_insight: "Análisis del examinador",
        feature_all_tools: "Todas las herramientas Study+",
        feature_marker: "AI Tutor — The Marker",
        feature_full_history: "Historial completo",
        feature_priority: "Soporte prioritario",
        common_loading: "Cargando...",
        common_error: "Algo salió mal",
        common_success: "¡Éxito!",
        common_copied: "¡Copiado!",
        common_save: "Guardar",
        common_cancel: "Cancelar",
        common_close: "Cerrar",
        common_or: "o",
    },
    "ko": {
        nav_examanswer: "시험답안",
        nav_studytools: "학습도구",
        nav_upgrade: "업그레이드",
        nav_settings: "설정",
        nav_signin: "로그인",
        landing_hero_title: "시험관이",
        landing_hero_highlight: "인정하는 답안 작성",
        landing_hero_subtitle: "시험위원회의 채점 기준에 맞게 설계된 AI 기반 답안으로 시험 준비를 혁신하세요.",
        landing_cta_start: "무료로 시작",
        landing_cta_plans: "요금제 보기",
        landing_benefit_1: "시험위원회에 맞춤화된 답안",
        landing_benefit_2: "공식 채점 기준 준수",
        landing_benefit_3: "시험관 수준의 피드백",
        landing_benefit_4: "10개 이상 국가 및 교육 시스템 지원",
        landing_features_title: "성공에 필요한 모든 것",
        landing_features_subtitle: "시험 성공을 위한 강력한 도구",
        landing_cta_title: "시험을 잘 볼 준비가 되셨나요?",
        landing_cta_subtitle: "이미 MarkUp으로 더 나은 답안을 작성하는 수천 명의 학생들과 함께하세요.",
        landing_cta_button: "더 나은 답안 작성 시작",
        auth_welcome: "다시 오신 것을 환영합니다",
        auth_create: "계정 만들기",
        auth_signin_subtitle: "시험 준비를 계속하려면 로그인하세요",
        auth_signup_subtitle: "오늘부터 더 나은 시험 답안을 작성하세요",
        auth_name: "이름",
        auth_name_placeholder: "이름",
        auth_email: "이메일",
        auth_email_placeholder: "you@example.com",
        auth_password: "비밀번호",
        auth_signin_btn: "로그인",
        auth_signup_btn: "계정 만들기",
        auth_signing_in: "로그인 중...",
        auth_creating: "계정 생성 중...",
        auth_no_account: "계정이 없으신가요? 가입하세요",
        auth_have_account: "이미 계정이 있으신가요? 로그인",
        settings_title: "설정",
        settings_subtitle: "교육 수준, 시험위원회 및 언어 설정",
        settings_education_title: "교육 설정",
        settings_education_subtitle: "답안이 시험위원회 요구사항에 맞게 조정됩니다",
        settings_country: "국가",
        settings_country_placeholder: "국가 선택",
        settings_level: "교육 수준",
        settings_level_placeholder: "수준 선택",
        settings_level_first: "먼저 국가를 선택하세요",
        settings_board: "시험위원회",
        settings_board_placeholder: "시험위원회 선택",
        settings_board_first: "먼저 수준을 선택하세요",
        settings_language_title: "언어",
        settings_language_subtitle: "인터페이스 언어 선택",
        settings_appearance_title: "테마",
        settings_appearance_subtitle: "밝은 테마와 어두운 테마 전환",
        settings_light: "밝게",
        settings_dark: "어둡게",
        settings_save: "저장 및 계속",
        settings_saving: "저장 중...",
        settings_summary: "답안 기준",
        settings_summary_in: "언어:",
        exam_title: "시험답안",
        exam_subtitle: "맞춤 답안 생성:",
        exam_setup_required: "설정 필요",
        exam_setup_message: "먼저 국가, 교육 수준 및 시험위원회를 설정하세요.",
        exam_go_settings: "설정으로 이동",
        exam_your_question: "질문 입력",
        exam_question_subtitle: "시험 질문을 입력하면 모범 답안을 생성합니다",
        exam_subject: "과목",
        exam_subject_placeholder: "과목 선택",
        exam_task_type: "문제 유형",
        exam_question: "질문",
        exam_question_placeholder: "시험 질문을 입력하세요...",
        exam_marks: "배점 (선택)",
        exam_marks_hint: "이 질문의 배점은?",
        exam_insight_title: "시험관 분석",
        exam_insight_on: "예상 등급 및 개선 팁 받기",
        exam_insight_off: "Study+ 또는 Pro 필요",
        exam_generate: "답안 생성",
        exam_generating: "생성 중...",
        exam_model_answer: "모범 답안",
        exam_answer_placeholder: "모범 답안이 여기에 표시됩니다",
        exam_answer_hint: "질문을 입력하고 생성을 클릭하세요",
        exam_copy: "복사",
        tools_title: "학습 도구",
        tools_subtitle: "시험 준비를 향상시키는 강력한 도구",
        tools_youtube_title: "YouTube → 노트",
        tools_youtube_desc: "YouTube 동영상을 구조화된 노트로 변환",
        tools_flashcards_title: "플래시카드",
        tools_flashcards_desc: "AI로 플래시카드 생성",
        tools_marker_title: "The Marker AI",
        tools_marker_desc: "답안에 대한 전문가 피드백",
        tools_required: "필요",
        tools_unlock: "잠금 해제",
        tools_unlock_all: "모든 도구 잠금 해제",
        tools_unlock_message: "Study+ 또는 Pro로 YouTube 노트, 플래시카드, The Marker AI에 액세스하세요.",
        youtube_title: "YouTube → 노트",
        youtube_subtitle: "동영상을 명확하고 간결한 노트로 변환",
        youtube_url: "YouTube URL",
        youtube_url_placeholder: "https://youtube.com/watch?v=...",
        youtube_or_paste: "또는 자막을 수동으로 붙여넣기",
        youtube_manual_title: "수동 자막 필요",
        youtube_manual_message: "YouTube가 자동 추출을 차단하고 있습니다. 자막을 복사하여 아래에 붙여넣으세요.",
        youtube_manual_tip: "팁: YouTube에서 \"...\" → \"자막 표시\" → 전체 선택 → 복사",
        youtube_paste_transcript: "자막 붙여넣기",
        youtube_paste_placeholder: "여기에 자막을 붙여넣으세요...",
        youtube_back: "뒤로",
        youtube_generate: "노트 생성",
        youtube_generating: "생성 중...",
        youtube_notes: "생성된 노트",
        youtube_empty: "YouTube URL을 붙여넣어 노트 생성",
        youtube_empty_hint: "자막이 있는 교육용 동영상에 가장 적합",
        youtube_extracting: "동영상 추출 및 요약 중...",
        flashcards_title: "플래시카드 생성",
        flashcards_study_title: "플래시카드 학습",
        flashcards_subtitle: "모든 주제에 대한 AI 플래시카드 생성",
        flashcards_study_subtitle: "카드를 클릭하여 뒤집기",
        flashcards_subject: "과목",
        flashcards_subject_placeholder: "예: 생물학",
        flashcards_topic: "주제",
        flashcards_topic_placeholder: "예: 세포 분열",
        flashcards_count: "카드 수",
        flashcards_max: "최대: 100",
        flashcards_generate: "생성",
        flashcards_generating: "생성 중",
        flashcards_new: "새 카드 생성",
        flashcards_question: "질문",
        flashcards_answer: "답변",
        flashcards_click_reveal: "클릭하여 답변 보기",
        flashcards_click_question: "클릭하여 질문 보기",
        flashcards_card: "카드",
        flashcards_of: "/",
        flashcards_reset: "초기화",
        flashcards_previous: "이전",
        flashcards_next: "다음",
        marker_title: "The Marker AI",
        marker_subtitle: "전문가 피드백:",
        marker_locked_message: "왜 특정 답안이 높은 점수를 받는지 전문가 피드백을 받으세요.",
        marker_pro_feature: "Pro 기능",
        marker_unlock: "The Marker AI 잠금 해제",
        marker_chat_title: "The Marker AI와 대화",
        marker_chat_subtitle: "채점 기준 및 답변 기술에 대해 질문하세요",
        marker_empty: "시험 기술에 대해 무엇이든 질문하세요",
        marker_hint_1: "12점 에세이를 어떻게 구성하나요?",
        marker_hint_2: "A* 평가 답안의 특징은?",
        marker_hint_3: "모든 평가 목표를 어떻게 달성하나요?",
        marker_placeholder: "질문하세요...",
        upgrade_title: "시험 준비 업그레이드",
        upgrade_subtitle: "강력한 기능 잠금 해제",
        upgrade_choose: "요금제 선택",
        upgrade_free: "무료",
        upgrade_free_desc: "기본 답안으로 시작",
        upgrade_studyplus: "Study+",
        upgrade_studyplus_desc: "향상된 학습 도구",
        upgrade_pro: "Pro",
        upgrade_pro_desc: "AI Tutor 포함 전체 기능",
        upgrade_popular: "인기",
        upgrade_best: "최고 가치",
        upgrade_current: "현재 요금제",
        upgrade_to: "업그레이드:",
        upgrade_forever: "영구",
        upgrade_month: "/월",
        upgrade_cancel: "모든 요금제에 ExamAnswer 포함. 언제든지 취소 가능.",
        upgrade_demo: "데모 모드: 업그레이드가 시뮬레이션됩니다.",
        feature_basic_exam: "기본 ExamAnswer",
        feature_limited_subjects: "제한된 과목",
        feature_no_history: "기록 없음",
        feature_no_insight: "분석 없음",
        feature_no_tools: "도구 없음",
        feature_no_tutor: "AI Tutor 없음",
        feature_full_exam: "전체 ExamAnswer",
        feature_multi_subject: "다중 과목",
        feature_youtube: "YouTube → 노트",
        feature_flashcards: "플래시카드",
        feature_save: "저장 및 기록",
        feature_insight: "시험관 분석",
        feature_all_tools: "모든 Study+ 도구",
        feature_marker: "AI Tutor — The Marker",
        feature_full_history: "전체 기록",
        feature_priority: "우선 지원",
        common_loading: "로딩 중...",
        common_error: "오류가 발생했습니다",
        common_success: "성공!",
        common_copied: "복사됨!",
        common_save: "저장",
        common_cancel: "취소",
        common_close: "닫기",
        common_or: "또는",
    },
    "ja": {
        nav_examanswer: "試験解答",
        nav_studytools: "学習ツール",
        nav_upgrade: "アップグレード",
        nav_settings: "設定",
        nav_signin: "ログイン",
        landing_hero_title: "試験官が",
        landing_hero_highlight: "評価する解答を書く",
        landing_hero_subtitle: "試験委員会の採点基準に合わせて設計されたAI解答で、試験準備を変革しましょう。",
        landing_cta_start: "無料で始める",
        landing_cta_plans: "プラン表示",
        landing_benefit_1: "試験委員会に合わせた解答",
        landing_benefit_2: "公式採点基準に準拠",
        landing_benefit_3: "試験官レベルのフィードバック",
        landing_benefit_4: "10以上の国と教育システムをサポート",
        landing_features_title: "成功に必要なすべて",
        landing_features_subtitle: "試験成功のための強力なツール",
        landing_cta_title: "試験に合格する準備はできましたか？",
        landing_cta_subtitle: "すでにMarkUpでより良い解答を書いている何千人もの学生に参加しましょう。",
        landing_cta_button: "より良い解答を書き始める",
        auth_welcome: "お帰りなさい",
        auth_create: "アカウント作成",
        auth_signin_subtitle: "試験準備を続けるにはログインしてください",
        auth_signup_subtitle: "今日からより良い試験解答を書き始めましょう",
        auth_name: "名前",
        auth_name_placeholder: "お名前",
        auth_email: "メール",
        auth_email_placeholder: "you@example.com",
        auth_password: "パスワード",
        auth_signin_btn: "ログイン",
        auth_signup_btn: "アカウント作成",
        auth_signing_in: "ログイン中...",
        auth_creating: "アカウント作成中...",
        auth_no_account: "アカウントをお持ちでないですか？登録",
        auth_have_account: "すでにアカウントをお持ちですか？ログイン",
        settings_title: "設定",
        settings_subtitle: "教育レベル、試験委員会、言語の設定",
        settings_education_title: "教育設定",
        settings_education_subtitle: "解答は試験委員会の要件に合わせて調整されます",
        settings_country: "国",
        settings_country_placeholder: "国を選択",
        settings_level: "教育レベル",
        settings_level_placeholder: "レベル選択",
        settings_level_first: "まず国を選択してください",
        settings_board: "試験委員会",
        settings_board_placeholder: "委員会選択",
        settings_board_first: "まずレベルを選択してください",
        settings_language_title: "言語",
        settings_language_subtitle: "インターフェース言語を選択",
        settings_appearance_title: "外観",
        settings_appearance_subtitle: "ライトテーマとダークテーマを切り替え",
        settings_light: "ライト",
        settings_dark: "ダーク",
        settings_save: "保存して続行",
        settings_saving: "保存中...",
        settings_summary: "解答基準",
        settings_summary_in: "言語：",
        exam_title: "試験解答",
        exam_subtitle: "カスタム解答生成：",
        exam_setup_required: "設定が必要",
        exam_setup_message: "まず国、教育レベル、試験委員会を設定してください。",
        exam_go_settings: "設定へ移動",
        exam_your_question: "質問入力",
        exam_question_subtitle: "試験問題を入力すると模範解答を生成します",
        exam_subject: "科目",
        exam_subject_placeholder: "科目を選択",
        exam_task_type: "問題タイプ",
        exam_question: "質問",
        exam_question_placeholder: "試験問題を入力してください...",
        exam_marks: "配点（任意）",
        exam_marks_hint: "この問題の配点は？",
        exam_insight_title: "試験官分析",
        exam_insight_on: "予想成績と改善のヒントを取得",
        exam_insight_off: "Study+またはProが必要",
        exam_generate: "解答を生成",
        exam_generating: "生成中...",
        exam_model_answer: "模範解答",
        exam_answer_placeholder: "模範解答がここに表示されます",
        exam_answer_hint: "質問を入力して生成をクリック",
        exam_copy: "コピー",
        tools_title: "学習ツール",
        tools_subtitle: "試験準備を強化する強力なツール",
        tools_youtube_title: "YouTube → ノート",
        tools_youtube_desc: "YouTube動画を構造化されたノートに変換",
        tools_flashcards_title: "フラッシュカード",
        tools_flashcards_desc: "AIでフラッシュカードを生成",
        tools_marker_title: "The Marker AI",
        tools_marker_desc: "解答に対する専門家フィードバック",
        tools_required: "必要",
        tools_unlock: "ロック解除",
        tools_unlock_all: "すべてのツールをロック解除",
        tools_unlock_message: "Study+またはProでYouTubeノート、フラッシュカード、The Marker AIにアクセス。",
        youtube_title: "YouTube → ノート",
        youtube_subtitle: "動画を明確で簡潔なノートに変換",
        youtube_url: "YouTube URL",
        youtube_url_placeholder: "https://youtube.com/watch?v=...",
        youtube_or_paste: "または字幕を手動で貼り付け",
        youtube_manual_title: "手動字幕が必要",
        youtube_manual_message: "YouTubeが自動抽出をブロックしています。字幕をコピーして下に貼り付けてください。",
        youtube_manual_tip: "ヒント：YouTubeで「...」→「文字起こしを表示」→全選択→コピー",
        youtube_paste_transcript: "字幕を貼り付け",
        youtube_paste_placeholder: "ここに字幕を貼り付け...",
        youtube_back: "戻る",
        youtube_generate: "ノート生成",
        youtube_generating: "生成中...",
        youtube_notes: "生成されたノート",
        youtube_empty: "YouTube URLを貼り付けてノート生成",
        youtube_empty_hint: "字幕付きの教育動画に最適",
        youtube_extracting: "動画を抽出・要約中...",
        flashcards_title: "フラッシュカード生成",
        flashcards_study_title: "フラッシュカード学習",
        flashcards_subtitle: "あらゆるトピックのAIフラッシュカードを作成",
        flashcards_study_subtitle: "カードをクリックして裏返す",
        flashcards_subject: "科目",
        flashcards_subject_placeholder: "例：生物学",
        flashcards_topic: "トピック",
        flashcards_topic_placeholder: "例：細胞分裂",
        flashcards_count: "カード数",
        flashcards_max: "最大：100",
        flashcards_generate: "生成",
        flashcards_generating: "生成中",
        flashcards_new: "新しいカード生成",
        flashcards_question: "質問",
        flashcards_answer: "回答",
        flashcards_click_reveal: "クリックして回答を表示",
        flashcards_click_question: "クリックして質問を表示",
        flashcards_card: "カード",
        flashcards_of: "/",
        flashcards_reset: "リセット",
        flashcards_previous: "前へ",
        flashcards_next: "次へ",
        marker_title: "The Marker AI",
        marker_subtitle: "専門家フィードバック：",
        marker_locked_message: "なぜ特定の解答が高得点を取るのか専門家フィードバックを受けましょう。",
        marker_pro_feature: "Pro機能",
        marker_unlock: "The Marker AIをロック解除",
        marker_chat_title: "The Marker AIとチャット",
        marker_chat_subtitle: "採点基準や解答テクニックについて質問",
        marker_empty: "試験テクニックについて何でも質問してください",
        marker_hint_1: "12点のエッセイをどう構成する？",
        marker_hint_2: "A*評価の解答の特徴は？",
        marker_hint_3: "すべての評価目標をどう達成する？",
        marker_placeholder: "質問してください...",
        upgrade_title: "試験準備をアップグレード",
        upgrade_subtitle: "強力な機能をロック解除",
        upgrade_choose: "プランを選択",
        upgrade_free: "無料",
        upgrade_free_desc: "基本解答から始める",
        upgrade_studyplus: "Study+",
        upgrade_studyplus_desc: "強化された学習ツール",
        upgrade_pro: "Pro",
        upgrade_pro_desc: "AI Tutor含む全機能",
        upgrade_popular: "人気",
        upgrade_best: "最高価値",
        upgrade_current: "現在のプラン",
        upgrade_to: "アップグレード：",
        upgrade_forever: "永久",
        upgrade_month: "/月",
        upgrade_cancel: "すべてのプランにExamAnswer含む。いつでもキャンセル可能。",
        upgrade_demo: "デモモード：アップグレードはシミュレーションです。",
        feature_basic_exam: "基本ExamAnswer",
        feature_limited_subjects: "限定科目",
        feature_no_history: "履歴なし",
        feature_no_insight: "分析なし",
        feature_no_tools: "ツールなし",
        feature_no_tutor: "AI Tutorなし",
        feature_full_exam: "完全ExamAnswer",
        feature_multi_subject: "複数科目",
        feature_youtube: "YouTube → ノート",
        feature_flashcards: "フラッシュカード",
        feature_save: "保存と履歴",
        feature_insight: "試験官分析",
        feature_all_tools: "全Study+ツール",
        feature_marker: "AI Tutor — The Marker",
        feature_full_history: "完全履歴",
        feature_priority: "優先サポート",
        common_loading: "読み込み中...",
        common_error: "エラーが発生しました",
        common_success: "成功！",
        common_copied: "コピーしました！",
        common_save: "保存",
        common_cancel: "キャンセル",
        common_close: "閉じる",
        common_or: "または",
    },
    "de": {
        nav_examanswer: "PrüfungsAntwort",
        nav_studytools: "Lerntools",
        nav_upgrade: "Upgrade",
        nav_settings: "Einstellungen",
        nav_signin: "Anmelden",
        landing_hero_title: "Schreibe Antworten, die",
        landing_hero_highlight: "Prüfer belohnen",
        landing_hero_subtitle: "Transformiere deine Prüfungsvorbereitung mit KI-generierten Antworten, die speziell für die Bewertungskriterien deiner Prüfungskommission entwickelt wurden.",
        landing_cta_start: "Kostenlos starten",
        landing_cta_plans: "Pläne anzeigen",
        landing_benefit_1: "Antworten auf deine Prüfungskommission zugeschnitten",
        landing_benefit_2: "Offizielle Bewertungskriterien befolgen",
        landing_benefit_3: "Prüfer-Level Einblicke erhalten",
        landing_benefit_4: "Unterstützung für 10+ Länder und Bildungssysteme",
        landing_features_title: "Alles was du brauchst um zu glänzen",
        landing_features_subtitle: "Leistungsstarke Tools für Prüfungserfolg",
        landing_cta_title: "Bereit deine Prüfungen zu bestehen?",
        landing_cta_subtitle: "Schließe dich tausenden Schülern an, die bereits bessere Prüfungsantworten mit MarkUp schreiben.",
        landing_cta_button: "Beginne besser zu schreiben",
        auth_welcome: "Willkommen zurück",
        auth_create: "Konto erstellen",
        auth_signin_subtitle: "Melde dich an um deine Prüfungsvorbereitung fortzusetzen",
        auth_signup_subtitle: "Beginne heute bessere Prüfungsantworten zu schreiben",
        auth_name: "Name",
        auth_name_placeholder: "Dein Name",
        auth_email: "E-Mail",
        auth_email_placeholder: "du@beispiel.com",
        auth_password: "Passwort",
        auth_signin_btn: "Anmelden",
        auth_signup_btn: "Konto erstellen",
        auth_signing_in: "Anmeldung...",
        auth_creating: "Konto wird erstellt...",
        auth_no_account: "Kein Konto? Registrieren",
        auth_have_account: "Bereits ein Konto? Anmelden",
        settings_title: "Einstellungen",
        settings_subtitle: "Konfiguriere dein Bildungsniveau, Prüfungskommission und Sprache",
        settings_education_title: "Bildungseinrichtung",
        settings_education_subtitle: "Deine Antworten werden an die Anforderungen deiner Kommission angepasst",
        settings_country: "Land",
        settings_country_placeholder: "Wähle dein Land",
        settings_level: "Bildungsniveau",
        settings_level_placeholder: "Niveau wählen",
        settings_level_first: "Zuerst Land wählen",
        settings_board: "Prüfungskommission",
        settings_board_placeholder: "Kommission wählen",
        settings_board_first: "Zuerst Niveau wählen",
        settings_language_title: "Sprache",
        settings_language_subtitle: "Wähle deine bevorzugte Sprache für die Oberfläche",
        settings_appearance_title: "Erscheinungsbild",
        settings_appearance_subtitle: "Zwischen hellem und dunklem Design wechseln",
        settings_light: "Hell",
        settings_dark: "Dunkel",
        settings_save: "Speichern und fortfahren",
        settings_saving: "Speichern...",
        settings_summary: "Deine Antworten folgen",
        settings_summary_in: "in",
        exam_title: "PrüfungsAntwort",
        exam_subtitle: "Generiere kommissionsspezifische Antworten für",
        exam_setup_required: "Einrichtung erforderlich",
        exam_setup_message: "Bitte konfiguriere zuerst dein Land, Bildungsniveau und Prüfungskommission.",
        exam_go_settings: "Zu Einstellungen",
        exam_your_question: "Deine Frage",
        exam_question_subtitle: "Gib deine Prüfungsfrage ein und wir generieren eine Musterantwort",
        exam_subject: "Fach",
        exam_subject_placeholder: "Fach auswählen",
        exam_task_type: "Aufgabentyp",
        exam_question: "Frage",
        exam_question_placeholder: "Tippe oder füge deine Prüfungsfrage hier ein...",
        exam_marks: "Punkte (optional)",
        exam_marks_hint: "Wie viele Punkte ist diese Frage wert?",
        exam_insight_title: "Prüfer-Einblick",
        exam_insight_on: "Notenvorhersage und Verbesserungstipps erhalten",
        exam_insight_off: "Erfordert Study+ oder Pro",
        exam_generate: "Antwort generieren",
        exam_generating: "Generiere...",
        exam_model_answer: "Musterantwort",
        exam_answer_placeholder: "Deine Musterantwort erscheint hier",
        exam_answer_hint: "Gib deine Frage ein und klicke auf Generieren",
        exam_copy: "Kopieren",
        tools_title: "Lerntools",
        tools_subtitle: "Leistungsstarke Tools zur Verbesserung deiner Vorbereitung",
        tools_youtube_title: "YouTube → Notizen",
        tools_youtube_desc: "Konvertiere YouTube-Videos in strukturierte Notizen",
        tools_flashcards_title: "Karteikarten",
        tools_flashcards_desc: "Generiere KI-Karteikarten für jedes Thema",
        tools_marker_title: "The Marker AI",
        tools_marker_desc: "Erhalte Experten-Feedback zu deinen Antworten",
        tools_required: "Erforderlich",
        tools_unlock: "Freischalten",
        tools_unlock_all: "Alle Tools freischalten",
        tools_unlock_message: "Erhalte Zugang zu YouTube Notizen, Karteikarten, The Marker AI mit Study+ oder Pro.",
        youtube_title: "YouTube → Notizen",
        youtube_subtitle: "Konvertiere ein Video in klare, prägnante Notizen",
        youtube_url: "YouTube URL",
        youtube_url_placeholder: "https://youtube.com/watch?v=...",
        youtube_or_paste: "Oder Transkript manuell einfügen",
        youtube_manual_title: "Manuelles Transkript erforderlich",
        youtube_manual_message: "YouTube blockiert die automatische Extraktion. Kopiere das Transkript und füge es unten ein.",
        youtube_manual_tip: "Tipp: Auf YouTube \"...\" → \"Transkript anzeigen\" → Alles auswählen → Kopieren",
        youtube_paste_transcript: "Transkript einfügen",
        youtube_paste_placeholder: "Transkript hier einfügen...",
        youtube_back: "Zurück",
        youtube_generate: "Notizen generieren",
        youtube_generating: "Generiere...",
        youtube_notes: "Generierte Notizen",
        youtube_empty: "YouTube URL einfügen um Notizen zu generieren",
        youtube_empty_hint: "Funktioniert am besten mit Lehrvideos mit Untertiteln",
        youtube_extracting: "Video wird extrahiert und zusammengefasst...",
        flashcards_title: "Karteikarten generieren",
        flashcards_study_title: "Karteikarten lernen",
        flashcards_subtitle: "Erstelle KI-Karteikarten zu jedem Thema",
        flashcards_study_subtitle: "Klicke auf eine Karte um sie umzudrehen",
        flashcards_subject: "Fach",
        flashcards_subject_placeholder: "z.B. Biologie",
        flashcards_topic: "Thema",
        flashcards_topic_placeholder: "z.B. Zellteilung",
        flashcards_count: "Anzahl der Karten",
        flashcards_max: "Max: 100",
        flashcards_generate: "Generieren",
        flashcards_generating: "Generiere",
        flashcards_new: "Neue Karten generieren",
        flashcards_question: "Frage",
        flashcards_answer: "Antwort",
        flashcards_click_reveal: "Klicken zum Aufdecken",
        flashcards_click_question: "Klicken für Frage",
        flashcards_card: "Karte",
        flashcards_of: "von",
        flashcards_reset: "Zurücksetzen",
        flashcards_previous: "Zurück",
        flashcards_next: "Weiter",
        marker_title: "The Marker AI",
        marker_subtitle: "Experten-Feedback für",
        marker_locked_message: "Erhalte Experten-Feedback warum bestimmte Antworten hohe Noten bekommen.",
        marker_pro_feature: "Pro Funktion",
        marker_unlock: "The Marker AI freischalten",
        marker_chat_title: "Mit The Marker AI chatten",
        marker_chat_subtitle: "Frage zu Bewertungsschemata und Antworttechniken",
        marker_empty: "Frage The Marker AI alles über Prüfungstechniken",
        marker_hint_1: "Wie strukturiere ich einen 12-Punkte-Aufsatz?",
        marker_hint_2: "Was macht eine A*-Bewertungsantwort aus?",
        marker_hint_3: "Wie erreiche ich alle Bewertungsziele?",
        marker_placeholder: "Frag The Marker AI...",
        upgrade_title: "Upgrade deine Prüfungsvorbereitung",
        upgrade_subtitle: "Leistungsstarke Funktionen freischalten",
        upgrade_choose: "Wähle deinen Plan",
        upgrade_free: "Kostenlos",
        upgrade_free_desc: "Mit Basisantworten starten",
        upgrade_studyplus: "Study+",
        upgrade_studyplus_desc: "Erweiterte Lerntools",
        upgrade_pro: "Pro",
        upgrade_pro_desc: "Alles inklusive AI Tutor",
        upgrade_popular: "Beliebt",
        upgrade_best: "Bester Wert",
        upgrade_current: "Aktueller Plan",
        upgrade_to: "Upgrade auf",
        upgrade_forever: "für immer",
        upgrade_month: "/Monat",
        upgrade_cancel: "Alle Pläne beinhalten ExamAnswer. Jederzeit kündbar.",
        upgrade_demo: "Demo-Modus: Upgrades sind simuliert.",
        feature_basic_exam: "Basis ExamAnswer",
        feature_limited_subjects: "Begrenzte Fächer",
        feature_no_history: "Kein Verlauf",
        feature_no_insight: "Keine Analyse",
        feature_no_tools: "Keine Tools",
        feature_no_tutor: "Kein AI Tutor",
        feature_full_exam: "Volles ExamAnswer",
        feature_multi_subject: "Mehrere Fächer",
        feature_youtube: "YouTube → Notizen",
        feature_flashcards: "Karteikarten",
        feature_save: "Speichern & Verlauf",
        feature_insight: "Prüfer-Einblick",
        feature_all_tools: "Alle Study+ Tools",
        feature_marker: "AI Tutor — The Marker",
        feature_full_history: "Vollständiger Verlauf",
        feature_priority: "Prioritäts-Support",
        common_loading: "Laden...",
        common_error: "Etwas ist schiefgelaufen",
        common_success: "Erfolg!",
        common_copied: "Kopiert!",
        common_save: "Speichern",
        common_cancel: "Abbrechen",
        common_close: "Schließen",
        common_or: "oder",
    }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        if (typeof window !== 'undefined') {
            return localStorage.getItem('markup-language') || 'en-GB';
        }
        return 'en-GB';
    });

    useEffect(() => {
        localStorage.setItem('markup-language', language);
    }, [language]);

    const t = (key) => {
        return translations[language]?.[key] || translations['en-GB']?.[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};

export const LANGUAGES = {
    "en-GB": "English (UK)",
    "en-US": "English (US)",
    "fr": "Français",
    "es": "Español",
    "ko": "한국어",
    "ja": "日本語",
    "de": "Deutsch"
};
